apiVersion: kubeflow.org/v1beta2
kind: TFJob
metadata:
  name: $(trainingName)
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      template:
        spec:
          containers:
          - name: tensorflow
            command:
            - /usr/bin/python
            - main.py
            - --tf-model-type=$(modelType)
            - --tf-learning-rate=$(learningRate)
            - --tf-num-epochs=$(numEpochs)
            - --tf-batch-size=$(batchSize)
            env:
            - name: modelType
              value: $(modelType)
            - name: learningRate
              value: $(learningRate)
            - name: numEpochs
              value: $(numEpochs)
            - name: batchSize
              value: $(batchSize)
            image: training-image
            workingDir: /opt
          restartPolicy: OnFailure
