apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Chief.yaml

namespace: kubeflow

generatorOptions:
  disableNameSuffixHash: true

configurations:
- params.yaml

vars:
- fieldref:
    fieldPath: data.name
  name: trainingName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: capsule-map-training
- fieldref:
    fieldPath: data.modelType
  name: modelType
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: capsule-map-training
- fieldref:
    fieldPath: data.learningRate
  name: learningRate
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: capsule-map-training
- fieldref:
    fieldPath: data.numEpochs
  name: numEpochs
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: capsule-map-training
- fieldref:
    fieldPath: data.batchSize
  name: batchSize
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: capsule-map-training
