apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

configurations:
- params.yaml

# TBD (jinchihe) Need move the image to base file once.
# the issue addressed: kubernetes-sigs/kustomize/issues/1040
# TBD (jinchihe) Need to update the image once
# the issue addressed: kubeflow/testing/issues/373
images:
- name: training-image
  newName: us.gcr.io/kubeflow-ps-learn/ak-kubeflow-train
  newTag: v1

vars:
- fieldref:
    fieldPath: data.GOOGLE_APPLICATION_CREDENTIALS
  name: GOOGLE_APPLICATION_CREDENTIALS
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: capsule-map-training
- fieldref:
    fieldPath: data.secretName
  name: secretName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: capsule-map-training
- fieldref:
    fieldPath: data.secretMountPath
  name: secretMountPath
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: capsule-map-training

patchesJson6902:
- path: Chief_patch.yaml
  target:
    group: kubeflow.org
    kind: TFJob
    name: $(trainingName)
    version: v1beta2
configMapGenerator:
- literals:
  - name=capsule-train-gcs
  - secretName=user-gcp-sa
  - secretMountPath=/var/secrets
  - GOOGLE_APPLICATION_CREDENTIALS=/var/secrets/user-gcp-sa.json
  - modelType=CNN
  - learningRate=0.0005
  - batchSize=25
  - numEpochs=5
  name: capsule-map-training
