apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- optimization.yaml

namespace: kubeflow

generatorOptions:
  disableNameSuffixHash: true
images:
- name: foo/bar
  newName: us.gcr.io/kubeflow-ps-learn/ak-kubeflow-train
  newTag: v1
